receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:

exporters:
  debug:  # Replacing `logging` with `debug` exporter
  otlp:
    endpoint: "tempo:4317"  # Point to the Tempo service
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]  # Using `debug` exporter instead of `logging`
